# Generated by Django 5.1.3 on 2024-11-08 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="city",
        ),
        migrations.RemoveField(
            model_name="user",
            name="house_number",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_doctor",
        ),
        migrations.RemoveField(
            model_name="user",
            name="region",
        ),
        migrations.RemoveField(
            model_name="user",
            name="street",
        ),
    ]
