# Generated by Django 5.1.3 on 2024-11-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("user", "User"), ("manager", "Manager"), ("owner", "Owner")],
                default="user",
                max_length=20,
            ),
        ),
    ]
