services:
  web:
      build:
          context: .
          dockerfile: Dockerfile.prod
      command: bash -c "poetry run python manage.py runserver 0.0.0.0:8000"
      ports:
        - "8000:8000"
      depends_on:
          - db
          - redis
      environment:
          - REDIS_URL=redis://redis:6379/0
  db:
      image: postgres:latest
      env_file:
        - ./environment/prod.env
      volumes:
        - postgres_data:/var/lib/postgresql/data
      ports:
        - "5432:5432"
  redis:
      image: redis:latest
      ports:
        - "6379:6379"
      environment:
        - REDIS_REPLICATION_MODE=master
volumes:
  postgres_data: { }