services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    command: bash -c " poetry run python manage.py migrate &&
                       poetry run python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - chyhryn_network
    env_file:
      - ./environment/dev.env
    volumes:
      - .:/usr/src/app
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./environment/dev.env
    networks:
      - chyhryn_network
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
    env_file:
      - ./environment/dev.env
    networks:
      - chyhryn_network
volumes:
  postgres_data: {}
networks:
  chyhryn_network:
    driver: bridge