services:
  web:
      build:
          context: .
          dockerfile: Dockerfile
          target: prod
      container_name: web_prod
      command: bash -c "poetry run python manage.py runserver 0.0.0.0:8000"
      volumes:
        - .:/app
      ports:
        - "8000:8000"
      depends_on:
          - db
          - redis
      environment:
          - REDIS_URL=redis://redis:6379/0
      env_file:
          - ./environment/prod.env
  db:
      image: postgres:latest
      env_file:
        - ./environment/prod.env
      volumes:
        - postgres_data:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
  redis:
      image: redis:latest
      ports:
        - "6379:6379"
      environment:
        - REDIS_REPLICATION_MODE=master
      env_file:
        - ./environment/prod.env
  celery:
    image: celery:latest
    build:
      context: .
    container_name: celery
    command: poetry run celery -A first_django_app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
volumes:
  postgres_data: { }