[tool.poetry]
name = "djtasks"
version = "0.1.0"
description = "A simple Django project."
authors = ["Snikls <macks.chigrin@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
django = "^5.1.2"

[tool.poetry.packages]
include = [{ include = "djtasks" }]  # Назва основної папки з кодом

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
