# Generated by Django 5.1.2 on 2024-10-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=30)),
                ('house_number', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('is_doctor', models.BooleanField()),
            ],
        ),
    ]
